### ISSUE TITLE
Use something like getpass for password entry

### ISSUE THREAD

**Issue by dseisun** [GetThematic/ClientSDK#2]
Echoing the password in my terminal is bad: https://github.com/GetThematic/ClientSDK/blob/master/thematic_client_sdk/scripts/interactive_auth.py#L12

**Comment by dseisun** [comment]
Python stdlib has something around this: https://docs.python.org/2/library/getpass.html

**Comment by nshgraph** [comment]
Thanks for the suggestion. I've implemented the suggested method and the password is no longer echoed to the terminal
